
spring.datasource.url=jdbc:postgresql://localhost:5432/iot_devices
spring.datasource.username=postgres
spring.datasource.password=1896
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
logging.level.com.example.demo=INFO
server.port=8085
spring.cache.type=simple
logging.level.org.hibernate.orm.jdbc.bind=TRACE

logging.level.org.hibernate.SQL=DEBUG
